name: Update Pitching Stats

on:
  schedule:
    - cron: '0 3 * * 1'  # Runs every Monday at 3 AM UTC
  workflow_dispatch:      # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib seaborn

    - name: Generate pitching stats charts
      run: python pitching_chart.py

    - name: Generate pitching trends charts
      run: python trend_pitching.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update pitching stats and trends [skip ci]" || echo "No changes to commit"
        git pull --rebase
        git push
