name: Update Prediction Tracking

on:
  workflow_dispatch: {}  # Minimalist workflow_dispatch trigger that will definitely work
  schedule:
    - cron: '30 14 * * *'  # Runs daily at 14:30 UTC (main branch only), after award predictions

jobs:
  update-prediction-tracking:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Skip scheduled runs on preview branch
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn numpy
        timeout-minutes: 5

      - name: Archive current predictions
        run: |
          # Create prediction history directory if it doesn't exist
          mkdir -p docs/prediction_history
          
          # Copy today's predictions to history with timestamp
          if [ -f "docs/award_predictions.json" ]; then
            cp docs/award_predictions.json docs/prediction_history/predictions_$(date +%F).json
            echo "✓ Archived today's predictions"
          else
            echo "Warning: No award predictions found to archive"
          fi
        timeout-minutes: 2
        continue-on-error: true

      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            COMMIT_MSG="Update prediction tracking [skip ci]"
            FILE_PATTERN="docs/prediction_history/*.json"
            
            git add $FILE_PATTERN
            git commit -m "$COMMIT_MSG"
            git push origin ${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
        timeout-minutes: 5
