name: Weekly Batting Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hung jobs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # Enable pip caching

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn
        timeout-minutes: 5

      - name: Run Batting Chart Script
        run: |
          python batting_chart.py || exit 1
        timeout-minutes: 5
        continue-on-error: false

      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/*.png docs/*.html docs/last_updated.txt || true
            git commit -m "Update batting charts [skip ci]"
            git pull --rebase
            git push
          else
            echo "No changes to commit"
          fi
        timeout-minutes: 2

      - name: Check for failures
        if: failure()
        run: |
          echo "::error::Workflow failed! Check the logs for details."
          exit 1
