name: Update Prediction Tracking

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 15:00 UTC after MVP/Cy Young updates
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-prediction-tracking:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn numpy
        timeout-minutes: 5

      - name: Run prediction tracking
        run: |
          export OUTPUT_PATH="docs"
          python prediction_tracker.py || exit 1
        timeout-minutes: 5

      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            git fetch origin main
            git reset --hard origin/main
            
            # Re-run after reset
            python prediction_tracker.py || exit 1
            
            git add docs/prediction_history/ docs/prediction_accuracy* docs/actual_winners.json
            git commit -m "Update prediction tracking and accuracy analysis [skip ci]"
            git push origin main
          else
            echo "No changes to commit"
          fi
        timeout-minutes: 2
