name: Update Batting Stats

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC (adjust if needed)
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  update-batting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybaseball matplotlib seaborn pandas

    - name: Run batting chart script
      run: python batting_chart.py

    - name: Archive current batting stats
      run: |
        mkdir -p archive
        cp docs/batting_stats.csv archive/batting_$(date +%F).csv

    - name: Run batting trend chart script
      run: python trend_batting.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/ archive/
        git commit -m "Update batting stats and trends [skip ci]" || echo "No changes to commit"
        git push
