name: Update Pitching Stats

on:
  schedule:
    - cron: '0 3 * * 1'  # Runs every Monday at 3 AM UTC
  workflow_dispatch:      # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hung jobs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for trends

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'  # Enable pip caching

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybaseball pandas matplotlib seaborn
      timeout-minutes: 5

    - name: Generate pitching stats charts
      run: |
        python pitching_chart.py || exit 1
      timeout-minutes: 5
      continue-on-error: false

    - name: Generate pitching trends charts
      run: |
        python trend_pitching.py || exit 1
      timeout-minutes: 5
      continue-on-error: false

    - name: Archive current pitching stats
      run: |
        mkdir -p archive
        if [ -f "docs/season_stats.csv" ]; then
          cp docs/season_stats.csv archive/pitching_$(date +%F).csv
        fi
      timeout-minutes: 2

    - name: Commit and push changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Handle potential conflicts with retry logic
          for i in {1..3}; do
            git fetch origin main
            git reset --hard origin/main
            
            # Re-run the scripts after reset
            python pitching_chart.py || exit 1
            python trend_pitching.py || exit 1
            
            # Archive again after reset
            mkdir -p archive
            if [ -f "docs/season_stats.csv" ]; then
              cp docs/season_stats.csv archive/pitching_$(date +%F).csv
            fi
            
            # Add files that exist
            git add docs/
            git add archive/
            git commit -m "Update pitching stats and trends [skip ci]"
            
            # Try to push with retry
            if git push origin main; then
              echo "Push successful on attempt $i"
              break
            else
              echo "Push failed on attempt $i, retrying..."
              sleep 5
            fi
            
            if [ $i -eq 3 ]; then
              echo "All push attempts failed"
              exit 1
            fi
          done
        else
          echo "No changes to commit"
        fi
      timeout-minutes: 5

    - name: Check for failures
      if: failure()
      run: |
        echo "::error::Workflow failed! Check the logs for details."
        exit 1
