name: Update MVP and Cy Young Predictions

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 14:00 UTC (after batting stats)
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-award-predictions:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybaseball pandas matplotlib seaborn numpy
        timeout-minutes: 5

      - name: Generate award predictions
        run: |
          python mvp_cy_young_calculator.py || exit 1
        timeout-minutes: 10
        continue-on-error: false

      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            # Handle potential conflicts
            git fetch origin main
            git reset --hard origin/main
            
            # Re-run the script after reset
            python mvp_cy_young_calculator.py || exit 1
            
            # Commit changes
            git add docs/award_predictions.json docs/al_mvp_predictions.csv docs/nl_mvp_predictions.csv docs/al_cy_young_predictions.csv docs/nl_cy_young_predictions.csv
            git commit -m "Update MVP and Cy Young award predictions [skip ci]"
            git push origin main
          else
            echo "No changes to commit"
          fi
        timeout-minutes: 2

      - name: Check for failures
        if: failure()
        run: |
          echo "::error::MVP/Cy Young predictions workflow failed! Check the logs for details."
          exit 1